# Automatically Generated Makefile by EDE.
# For use with: make
#
# DO NOT MODIFY THIS FILE OR YOUR CHANGES MAY BE LOST.
# EDE is the Emacs Development Environment.
# http://cedet.sourceforge.net/ede.shtml
# 
LDFLAGS=-lSDL -lSDL_image
CFLAGS=-I/usr/include/SDL -Imodelo -D_GNU_SOURCE=1 -D_REENTRANT

top=
ede_FILES=Project.ede Makefile

cavernization_SOURCES=main.cpp modelo/terrenos.cpp UI/input.cpp modelo/mapa.cpp modelo/terrenos.cpp UI/dibujar.cpp modelo/casa.cpp modelo/jugador.cpp modelo/arbol.cpp modelo/personaje.cpp
cavernization_OBJ= main.o modelo/terrenos.o UI/input.o modelo/mapa.o modelo/terrenos.o UI/dibujar.o modelo/casa.o modelo/jugador.o modelo/arbol.o modelo/personaje.o
CXX= g++
CXX_COMPILE=$(CXX) $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS)
CXX_DEPENDENCIES=-Wp,-MD,.deps/$(*F).P
CXX_LINK=$(CXX) $(CFLAGS) $(LDFLAGS) -L. -o $@
VERSION=1.0
DISTDIR=$(top)cavernization-$(VERSION)
top_builddir = 

DEP_FILES=.deps/main.P .deps/terrenos.P .deps/input.P .deps/mapa.P .deps/terrenos.P .deps/dibujar.P .deps/casa.P .deps/jugador.P .deps/arbol.P .deps/personaje.P .deps/terreno.P .deps/dibujar.P .deps/input.P .deps/objetomapa.P .deps/casa.P .deps/jugador.P .deps/objetoconduenio.P .deps/personaje.P .deps/monumento.P .deps/fiel.P .deps/edificio.P .deps/main.P

all: cavernization

DEPS_MAGIC := $(shell mkdir .deps > /dev/null 2>&1 || :)
-include $(DEP_FILES)

: 
	

%.o: %.cpp
	@echo '$(CXX_COMPILE) -c $<'; \
	$(CXX_COMPILE) $(CXX_DEPENDENCIES) -o $@ -c $<

cavernization: $(cavernization_OBJ)
	$(CXX_LINK) $^

tags: 


clean:
	rm -f *.o *.obj .deps/*.P .lo

.PHONY: dist

dist:
	rm -rf $(DISTDIR)
	mkdir $(DISTDIR)
	cp $(cavernization_SOURCES) $(ede_FILES) $(DISTDIR)
	tar -cvzf $(DISTDIR).tar.gz $(DISTDIR)
	rm -rf $(DISTDIR)

Makefile: Project.ede
	@echo Makefile is out of date!  It needs to be regenerated by EDE.
	@echo If you have not modified Project.ede, you can use 'touch' to update the Makefile time stamp.
	@false



# End of Makefile
